/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness check */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a student account */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log in and receive an access token */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current user profile */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/campus/buildings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List or search campus buildings and locations */
        get: operations["listBuildings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/campus/buildings/{building_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one building */
        get: operations["getBuilding"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/campus/route": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Walking route from a point to a building */
        get: operations["getRoute"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/faculties": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List faculties */
        get: operations["listFaculties"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/departments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List departments */
        get: operations["listDepartments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/departments/{department_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one department */
        get: operations["getDepartment"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/departments/{department_id}/lecturers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lecturers in a department */
        get: operations["listDepartmentLecturers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/departments/{department_id}/courses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Courses in a department */
        get: operations["listDepartmentCourses"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/departments/{department_id}/class-reps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Class representatives in a department */
        get: operations["listDepartmentClassReps"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/departments/{department_id}/timetable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Timetable entries for a department */
        get: operations["getDepartmentTimetable"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lecturers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search lecturers by name */
        get: operations["searchLecturers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lecturers/{lecturer_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one lecturer */
        get: operations["getLecturer"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/announcements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List announcements (newest first) */
        get: operations["listAnnouncements"];
        put?: never;
        /** Publish an announcement (admin roles only) */
        post: operations["createAnnouncement"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/announcements/{announcement_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one announcement */
        get: operations["getAnnouncement"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set the verification status of a record (admin roles only) */
        post: operations["verifyRecord"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Everything changed since a timestamp (primes the offline cache in one request)
         * @description Without `since`, returns the full dataset (`full: true`).
         *     With `since`, returns only rows created/updated after it, plus ids deleted since then.
         */
        get: operations["sync"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            detail: unknown;
        };
        /** @enum {string} */
        UserRole: "student" | "class_rep" | "department_admin" | "faculty_admin" | "sug" | "super_admin";
        /** @enum {string} */
        BuildingType: "faculty" | "department" | "lecture_hall" | "hostel" | "admin" | "library" | "sports" | "food" | "health" | "worship" | "gate" | "other";
        /** @enum {string} */
        AnnouncementScope: "university" | "sug" | "faculty" | "department";
        /** @enum {string} */
        VerificationStatus: "unverified" | "verified" | "outdated";
        Verification: {
            status: components["schemas"]["VerificationStatus"];
            /** @description Where this information came from */
            source?: string | null;
            /** Format: uuid */
            verified_by?: string | null;
            /** Format: date-time */
            verified_at?: string | null;
        };
        RegisterRequest: {
            full_name: string;
            /** Format: email */
            email: string;
            password: string;
            matric_no?: string | null;
            /** Format: uuid */
            department_id?: string | null;
            /** @example 100 */
            level?: number | null;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        TokenResponse: {
            access_token: string;
            /** @enum {string} */
            token_type: "bearer";
            /** @description Seconds until expiry */
            expires_in: number;
        };
        User: {
            /** Format: uuid */
            id: string;
            full_name: string;
            /** Format: email */
            email: string;
            role: components["schemas"]["UserRole"];
            matric_no?: string | null;
            /** Format: uuid */
            department_id?: string | null;
            /** Format: uuid */
            faculty_id?: string | null;
            level?: number | null;
        };
        Faculty: {
            /** Format: uuid */
            id: string;
            name: string;
            short_name?: string | null;
            verification: components["schemas"]["Verification"];
            /** Format: date-time */
            updated_at: string;
        };
        Department: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            faculty_id: string;
            name: string;
            short_name?: string | null;
            hod_name?: string | null;
            office_location?: string | null;
            verification: components["schemas"]["Verification"];
            /** Format: date-time */
            updated_at: string;
        };
        Lecturer: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            department_id: string;
            full_name: string;
            /** @example Dr. */
            title?: string | null;
            /** @example Senior Lecturer */
            rank?: string | null;
            /** @description Official school email only */
            email?: string | null;
            office_location?: string | null;
            specialization?: string | null;
            verification: components["schemas"]["Verification"];
            /** Format: date-time */
            updated_at: string;
        };
        Course: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            department_id: string;
            /** @example CSC101 */
            code: string;
            title: string;
            units: number;
            /** @example 100 */
            level: number;
            /** @enum {integer} */
            semester: 1 | 2;
            verification: components["schemas"]["Verification"];
            /** Format: date-time */
            updated_at: string;
        };
        ClassRep: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            department_id: string;
            level: number;
            full_name: string;
            /** @description Only present when the class rep has given consent (NDPR) */
            contact?: string | null;
            verification: components["schemas"]["Verification"];
            /** Format: date-time */
            updated_at: string;
        };
        Building: {
            /** Format: uuid */
            id: string;
            name: string;
            type: components["schemas"]["BuildingType"];
            description?: string | null;
            /** Format: double */
            lat: number;
            /** Format: double */
            lng: number;
            verification: components["schemas"]["Verification"];
            /** Format: date-time */
            updated_at: string;
        };
        TimetableEntry: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            department_id: string;
            level: number;
            /** @enum {integer} */
            semester: 1 | 2;
            /** Format: uuid */
            course_id: string;
            /** @description 1 = Monday */
            day_of_week: number;
            /** @example 08:00 */
            start_time: string;
            /** @example 10:00 */
            end_time: string;
            /** Format: uuid */
            venue_building_id?: string | null;
            venue_note?: string | null;
            verification: components["schemas"]["Verification"];
            /** Format: date-time */
            updated_at: string;
        };
        Announcement: {
            /** Format: uuid */
            id: string;
            title: string;
            body: string;
            scope: components["schemas"]["AnnouncementScope"];
            /** Format: uuid */
            faculty_id?: string | null;
            /** Format: uuid */
            department_id?: string | null;
            /** Format: uuid */
            author_id: string;
            /** Format: date-time */
            published_at: string;
            /** Format: date-time */
            expires_at?: string | null;
            verification: components["schemas"]["Verification"];
            /** Format: date-time */
            updated_at: string;
        };
        AnnouncementCreate: {
            title: string;
            body: string;
            scope: components["schemas"]["AnnouncementScope"];
            /** Format: uuid */
            faculty_id?: string | null;
            /** Format: uuid */
            department_id?: string | null;
            /** Format: date-time */
            expires_at?: string | null;
        };
        VerifyRequest: {
            /** @enum {string} */
            entity_type: "faculties" | "departments" | "lecturers" | "courses" | "class_reps" | "buildings" | "timetable_entries" | "announcements";
            /** Format: uuid */
            entity_id: string;
            status: components["schemas"]["VerificationStatus"];
            source?: string | null;
        };
        RouteResponse: {
            distance_m: number;
            duration_s: number;
            /** @description GeoJSON LineString, coordinates as [lng, lat] */
            geometry: {
                [key: string]: unknown;
            };
        };
        SyncResponse: {
            /**
             * Format: date-time
             * @description Store this and send it as `since` next time
             */
            server_time: string;
            /** @description True when `since` was omitted (client should replace its cache) */
            full: boolean;
            faculties: components["schemas"]["Faculty"][];
            departments: components["schemas"]["Department"][];
            lecturers: components["schemas"]["Lecturer"][];
            courses: components["schemas"]["Course"][];
            class_reps: components["schemas"]["ClassRep"][];
            buildings: components["schemas"]["Building"][];
            timetable_entries: components["schemas"]["TimetableEntry"][];
            announcements: components["schemas"]["Announcement"][];
            /** @description Ids deleted since `since`, keyed by collection name */
            deleted: {
                [key: string]: string[];
            };
        };
    };
    responses: {
        /** @description Missing or invalid credentials */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Not allowed for this role */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Already exists */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Invalid input */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        Limit: number;
        Offset: number;
        BuildingId: string;
        DepartmentId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example ok */
                        status: string;
                    };
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Account created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Logged in */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["ValidationError"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listBuildings: {
        parameters: {
            query?: {
                q?: string;
                type?: components["schemas"]["BuildingType"];
                limit?: components["parameters"]["Limit"];
                offset?: components["parameters"]["Offset"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Buildings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Building"][];
                };
            };
        };
    };
    getBuilding: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                building_id: components["parameters"]["BuildingId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Building */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Building"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getRoute: {
        parameters: {
            query: {
                from_lat: number;
                from_lng: number;
                to_building_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Route */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RouteResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listFaculties: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Faculties */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Faculty"][];
                };
            };
        };
    };
    listDepartments: {
        parameters: {
            query?: {
                faculty_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Departments */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Department"][];
                };
            };
        };
    };
    getDepartment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                department_id: components["parameters"]["DepartmentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Department */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Department"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listDepartmentLecturers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                department_id: components["parameters"]["DepartmentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lecturers */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Lecturer"][];
                };
            };
        };
    };
    listDepartmentCourses: {
        parameters: {
            query?: {
                level?: number;
                semester?: 1 | 2;
            };
            header?: never;
            path: {
                department_id: components["parameters"]["DepartmentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Courses */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Course"][];
                };
            };
        };
    };
    listDepartmentClassReps: {
        parameters: {
            query?: {
                level?: number;
            };
            header?: never;
            path: {
                department_id: components["parameters"]["DepartmentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Class representatives */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClassRep"][];
                };
            };
        };
    };
    getDepartmentTimetable: {
        parameters: {
            query?: {
                level?: number;
                semester?: 1 | 2;
            };
            header?: never;
            path: {
                department_id: components["parameters"]["DepartmentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Timetable */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimetableEntry"][];
                };
            };
        };
    };
    searchLecturers: {
        parameters: {
            query?: {
                q?: string;
                limit?: components["parameters"]["Limit"];
                offset?: components["parameters"]["Offset"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lecturers */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Lecturer"][];
                };
            };
        };
    };
    getLecturer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lecturer_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lecturer */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Lecturer"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listAnnouncements: {
        parameters: {
            query?: {
                scope?: components["schemas"]["AnnouncementScope"];
                faculty_id?: string;
                department_id?: string;
                limit?: components["parameters"]["Limit"];
                offset?: components["parameters"]["Offset"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Announcements */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Announcement"][];
                };
            };
        };
    };
    createAnnouncement: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnnouncementCreate"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Announcement"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationError"];
        };
    };
    getAnnouncement: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                announcement_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Announcement */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Announcement"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    verifyRecord: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyRequest"];
            };
        };
        responses: {
            /** @description Updated */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationError"];
        };
    };
    sync: {
        parameters: {
            query?: {
                since?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Changes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncResponse"];
                };
            };
        };
    };
}
